### PR TITLE
🤖 Update readme.md with RAG example

### PR DESCRIPTION
**Pull request by kadirnar**

### CODE REVIEW

**Comment by kadirnar** [comment]
@akashAD98 

Could you check the readme.md file? Which input formats does it support? Just str? Does it support extensions such as mp4, pdf, audio, md?

We need it. How can we do this?
https://github.com/safevideo/autollm/tree/main?tab=readme-ov-file#create-a-query-engine-in-seconds

**Comment by akashAD98** [comment]
@kadirnar in readme add question 
"give me a summary of the video? instead of What is mistral.?
so its more relavant

**Comment by akashAD98** [comment]
need to fix it

image

**Comment by akashAD98** [comment]
@kadirnar  Also, should we provide an option for users to specify their text input path?

Here's the general workflow:

Pass the YouTube link to the system, like so:

```
url = "https://www.youtube.com/watch?v=di3rHkEZuUw"
# Initialize the Speech to Text Pipeline with the specified model.
audio_path = download_and_convert_to_mp3(url)
pipeline = SpeechToTextPipeline(model_id="openai/whisper-large-v3")
```
## need to update saving .text part

```
with open("transcript.txt", "w") as file:
    file.write(transcript)
```

After processing, save the transcript as a text file in the same folder.

Use the RAG (Retrieval-Augmented Generation) model for asking questions about the video. By default, the system will use the transcript.txt file. Users can ask questions to gain insights from the video content.

There's no need to support PDF files in this scenario; text format will suffice. This workflow provides a complete end-to-end example for those who want to summarize YouTube videos or any other video content."

**Comment by kadirnar** [comment]
> @kadirnar Also, should we provide an option for users to specify their text input path?
> 
> Here's the general workflow:
> 
> Pass the YouTube link to the system, like so:
> 
> ```
> url = "https://www.youtube.com/watch?v=di3rHkEZuUw"
> # Initialize the Speech to Text Pipeline with the specified model.
> audio_path = download_and_convert_to_mp3(url)
> pipeline = SpeechToTextPipeline(model_id="openai/whisper-large-v3")
> ```
> 
> ## need to update saving .text part
> ```
> with open("transcript.txt", "w") as file:
>     file.write(transcript)
> ```
> 
> After processing, save the transcript as a text file in the same folder.
> 
> Use the RAG (Retrieval-Augmented Generation) model for asking questions about the video. By default, the system will use the transcript.txt file. Users can ask questions to gain insights from the video content.
> 
> There's no need to support PDF files in this scenario; text format will suffice. This workflow provides a complete end-to-end example for those who want to summarize YouTube videos or any other video content."

I understand There is no need right now. I can add it later. We shouldn't recognize manual models. Can you fix this?

https://github.com/kadirnar/whisper-plus/blob/main/whisperplus/pipelines/chatbot.py#L12

**Comment by akashAD98** [comment]
> > @kadirnar Also, should we provide an option for users to specify their text input path?
> > Here's the general workflow:
> > Pass the YouTube link to the system, like so:
> > ```
> > url = "https://www.youtube.com/watch?v=di3rHkEZuUw"
> > # Initialize the Speech to Text Pipeline with the specified model.
> > audio_path = download_and_convert_to_mp3(url)
> > pipeline = SpeechToTextPipeline(model_id="openai/whisper-large-v3")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## need to update saving .text part
> > ```
> > with open("transcript.txt", "w") as file:
> >     file.write(transcript)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After processing, save the transcript as a text file in the same folder.
> > Use the RAG (Retrieval-Augmented Generation) model for asking questions about the video. By default, the system will use the transcript.txt file. Users can ask questions to gain insights from the video content.
> > There's no need to support PDF files in this scenario; text format will suffice. This workflow provides a complete end-to-end example for those who want to summarize YouTube videos or any other video content."
> 
> I understand There is no need right now. I can add it later. We shouldn't recognize manual models. Can you fix this?
> 
> https://github.com/kadirnar/whisper-plus/blob/main/whisperplus/pipelines/chatbot.py#L12

can we add openai embedding model  there?

**Comment by akashAD98** [comment]
@kadirnar whats issue we are getting for that embedding model?

**Comment by kadirnar** [comment]
> @kadirnar whats issue we are getting for that embedding model?
> 
> should we add this?
> 
> ```
> from langchain.embeddings import OpenAIEmbeddings
> 
> embeddings_model = OpenAIEmbeddings(openai_api_key="...")
> ```
> 
> but need to provide the api ,that not possible for each user
> 
> below is also opensource
> 
> ```
> from langchain.embeddings import HuggingFaceEmbeddings
>  HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2',
>                                    model_kwargs={'device': 'cpu'})
> ```

I want the user to decide this. You must add model_path parameter to the function. When I want to change the model, I do not want to look at the source codes. We just have to do this by using the load_llm_model function.

**Comment by akashAD98** [comment]
@kadirnar got it ill work on it

**Pull request merged**
