### PR TITLE
Added the functionality to convert text to speech

### PR DESCRIPTION
**Pull request by GuldenizBektas**
* In the `Bark` folder, there is a pipeline to convert text to speech. The voice will be saved in the base folder if other is not specified.

* Additionally, in `whisperplus/pipelines/whisper.py` I got an error, so added ignore flag. It looks more clean when cloning the repo.

### CODE REVIEW

**Comment by kadirnar** [comment]
@GuldenizBektas ,
Thank you for your contribution❤️ I will merge it after fixing the bugs🚀

**Comment by GuldenizBektas** [comment]
Ow okay, I just considered BARK library. I can work with HF :)

**Comment by kadirnar** [comment]
Great. Can you move the codes to whisper/pipeline folder?

**Comment by GuldenizBektas** [comment]
I'll add the code when I'm available :( I haven't been available for a while.

**Pull request closed without merging**
