### PR TITLE
Feature/whisper rag

### PR DESCRIPTION
**Pull request by akashAD98**
Feature: https://github.com/kadirnar/whisper-plus/issues/13
Added support for RAG user can ask questions for video

image

### CODE REVIEW

**Comment by akashAD98** [comment]
requirements.txt for rag is
needed to update this part

```

!pip install lancedb
!pip install langchain
!pip install openai
!pip install sentence-transformers
!pip install ctransformers

```

**Comment by kadirnar** [comment]
> requirements.txt for rag is needed to update this part
> 
> ```
> 
> !pip install lancedb
> !pip install langchain
> !pip install openai
> !pip install sentence-transformers
> !pip install ctransformers
> ```

Can you create dev-requirements.txt?

**Comment by akashAD98** [comment]
image

i did & it passed all , can you check once @kadirnar

**Comment by kadirnar** [comment]
> image
> 
> i did & it passed all , can you check once @kadirnar

Thank you for your contribution. I will merge it after testing.

**Comment by kadirnar** [comment]
@akashAD98 should add it to the pipelines folder.

**Comment by akashAD98** [comment]
> @akashAD98 should add it to the pipelines folder.

okay im adding it

**Pull request closed without merging**
